### ISSUE TITLE
Services are not killed

### ISSUE THREAD

**Issue by SergeyPirogov** [aerokube/moon#105]
![image](https://user-images.githubusercontent.com/4622856/49721001-e8111780-fc69-11e8-9a32-375d808024ec.png)

**Comment by SergeyPirogov** [comment]
I use moon 1.2.0. After some time there are services that were not removed (see screenshot above). For now I delete them time to time manually. Would be nice to clean up services automatically

**Comment by vania-pooh** [comment]
@SergeyPirogov did you notice any OOMKilled pods? Could be related to #95.

**Comment by vania-pooh** [comment]
Fixed in aandryashin/moon#164.
