### ISSUE TITLE
PODS are hang out instead of delete

### ISSUE THREAD

**Issue by MaxSlapaev** [aerokube/moon#110]
Day bay day we face with issue that pods are not deleted even after session timeout expiration.

![image](https://user-images.githubusercontent.com/45286293/50476688-af936c80-09d1-11e9-96a0-fe3734bb157c.png)

State on UI:
![image](https://user-images.githubusercontent.com/45286293/50476707-ccc83b00-09d1-11e9-9984-0a46cb22db27.png)

**Comment by vania-pooh** [comment]
@MaxSlapaev could you show me what's inside `defender` container logs?
```
$ kubectl logs <pod-id> -c defender -n moon
```

**Comment by MaxSlapaev** [comment]
![image](https://user-images.githubusercontent.com/45286293/50478234-ce493180-09d8-11e9-831d-730a1d91b782.png)

**Comment by vania-pooh** [comment]
Fixed in aandryashin/moon#164, aandryashin/moon#165.
