### ISSUE TITLE
Ability to proxy to external hosts

### ISSUE THREAD

**Issue by benzman81** [aerokube/moon#117]
Hi,

we currently use your great products Selenoid and GGR for our grid. There we have 30 Internet explorers connected and 5 firefox and 5 chrome. Is this possible with Moon, too? If so, how would the configuration look like? Do the parallel sessions for the final pricing of moon also count the own 30 windows vms running the IE, or do only the sessions count that are getting spinned up in kubernetes.

We are happy with selenoid on docker, but we are migrating everthing to kubernetes and selenoid/ggr is the ony left over application on our docker-only host.

Regards,
Markus

**Comment by vania-pooh** [comment]
@benzman81 currently Moon is not able to proxy sessions to external virtual machines. Moon is billed depending on number of parallel Kubernetes pods with browsers. So we are currently investigating how we could distribute Docker containers with Windows browsers, e.g. Internet Explorer or Edge, from legal point of view. We are already able to launch such containers but don't show them for legal reasons. Having Docker images with IE - would you still need to proxy anything to external virtual machines?

**Comment by benzman81** [comment]
IE in Docker? If we wont need a Windows Server as Docker Host and no Licenses for Windows for it, then it would be fine, I think.

**Comment by vania-pooh** [comment]
@benzman81 yep, I think Microsoft will require to buy licenses, but this will work uniformly with the rest of browsers in Kubernetes.

**Comment by benzman81** [comment]
We currently use the free images from modern.ie. And how would your run IE in docker? Only solution I know is running docker on windows server...

**Comment by vania-pooh** [comment]
@benzman81 we'll show as soon as legal issues are resolved.

**Comment by benzman81** [comment]
Forgot about our mobile tests. Will that be possible, too? (Appium + iOS)

**Comment by vania-pooh** [comment]
@benzman81 Android already works with Moon. iOS - not yet. So if iOS is a blocker for migrating to Moon - we can consider adding configuration to proxy sessions to existing hosts. These will certainly excluded from license parallel sessions count as it is not Kubernetes.

**Comment by benzman81** [comment]
Would be a good option.

**Comment by vania-pooh** [comment]
Will do as follows.
```
"iOS": {
      "11.0": {
           "host": {
               "scheme": "http",
                "name": "some-host.example.com",
                "port": "4444",
                "username": "",
               "password": ""
      }
}
```

**Comment by vania-pooh** [comment]
@benzman81 after discussion - how about just running Ggr proxying iOS to VMs and all the rest to Moon?

**Comment by benzman81** [comment]
My understanding was, that Moon will replace ggr/ggr-ui/selenoid/selenoid-ui. Is Moon „just“ the selenoid part?

**Comment by vania-pooh** [comment]
@benzman81 yes, Moon is Ggr + Selenoid for Kubernetes. But for your case with `iOS` you can use Moon for everything except `iOS` and use already working `ggr` to proxy to iOS.

**Comment by benzman81** [comment]
can I combine it somehow into one hub url or would I end up with one hub url for mobile and one for webtests?

**Comment by vania-pooh** [comment]
@benzman81 yes, you will use Ggr URL and it will proxy either to your VMs or to Moon running in Kubernetes.

**Comment by vania-pooh** [comment]
Need to provide container that will work with external Selenium service or Ggr.

**Comment by vania-pooh** [comment]
I think this should have been fixed and is documented here: https://aerokube.com/moon/latest/#selenium-external-host
