### ISSUE TITLE
Browser containers immediately throwing 500

### ISSUE THREAD

**Issue by donofriov** [aerokube/moon#121]
When there are special characters (<, >, $, etc.) in the describe and it blocks of my test, the test will immediately throw a Selenium::WebDriver::Error::ServerError: with a status code 500.

![image](https://user-images.githubusercontent.com/4457953/51313402-76bc4580-1a1b-11e9-8408-d5d72e864228.png)
![image](https://user-images.githubusercontent.com/4457953/51313425-820f7100-1a1b-11e9-8852-12e1f4e59583.png)

As soon as I remove the `>` from the above test, it runs as it should.

![image](https://user-images.githubusercontent.com/4457953/51313474-a8351100-1a1b-11e9-9754-06b53292521d.png)
![image](https://user-images.githubusercontent.com/4457953/51313493-ae2af200-1a1b-11e9-931b-182a27f3a62f.png)

The moon pod is throwing this error:

[moon-6f54d98c6c-jg7zk moon] 2019/01/17 10:52:02 [SERVER_ERROR] [browsers] [80.110.103.14, 35.241.31.175, 10.168.0.23] [chrome-71-0-6edbc30c-355b-4b9e-adc6-283bc0c135a7] [Failed to execute templates: [invalid character 'x' in string escape code]] [0.00s]

**Comment by vania-pooh** [comment]
Capability is called `name`.

**Comment by vania-pooh** [comment]
Related to https://github.com/aerokube/moon/issues/97.

**Comment by vania-pooh** [comment]
@donofriov merged, available in `aerokube/moon:latest` and `aerokube/moon-api:latest`. Note that both images should be updated.

**Comment by donofriov** [comment]
@vania-pooh verified it's working, thank you!
