### ISSUE TITLE
Verbose log output / debug docker image inside

### ISSUE THREAD

**Issue by alexdyukov** [aerokube/moon#123]
Hey!

We have got a trouble with moon service in our k8s cluster, but didnt find any logs to help us to troubleshoot it. Is there any chance to add debug docker image or enviroment variable ( configmap ), which enables additional logging with huge verbosity?
Debug would be easy with this feature.

It would be nice if debug docker image will also have:
bash (or another shell)
dnsutils
trace/tcpdump

With love,
STC team

**Comment by vania-pooh** [comment]
1) Will add specified tools, pprof support and bash.
2) Regarding logging - we are already logging every event. Will describe in docs how to debug.
