### ISSUE TITLE
DNS resolution problems, pod hangs forever if failed to lookup

### ISSUE THREAD

**Issue by skudasov** [aerokube/moon#130]
Hello, we have some problem with CoreDNS cache, why in session *chrome-71-0-4d29b470-9abd-4094-99da-ac88caad0012* after first bad resolved request nothing happened? Pod and service was not killed. We know we can turn the cache off https://aerokube.com/moon/latest/#_features_not_working
Can we try to resolve it again from client?
[proxy-logs.log](https://github.com/aerokube/moon/files/2884598/proxy-logs.log)

**Comment by aandryashin** [comment]
We a working now to implement retry on client side in case of errors...

ср, 20 февр. 2019 г., 15:48 f4hrenh9it <notifications@github.com>:

**Comment by vania-pooh** [comment]
This one was implemented.
