### ISSUE TITLE
Curl example in Moon UI is incorrect

### ISSUE THREAD

**Issue by amberdemon** [aerokube/moon#145]
The example provided in the moon ui is incorrect for the value of sessionTimeout.

sessionTimeout is a string in the struct in Go and requires a unit of measurement.

The example is 
`curl -X POST 'http://127.0.0.1:4444/wd/hub/session' -d '{ 
            "desiredCapabilities":{
                "browserName":"chrome", 
                "version": "custom", 
                "platform":"ANY",
                "enableVNC": true,
                "name": "this.test.is.launched.by.curl",
                "sessionTimeout": 30
            }
        }'`

Resulting in the error
`{"status":13,"value":{"message":"Failed to parse request: json: cannot unmarshal number into Go struct field caps.sessionTimeout of type string"}}
`

The example should be 

`curl -X POST 'http://127.0.0.1:4444/wd/hub/session' -d '{ 
            "desiredCapabilities":{
                "browserName":"chrome", 
                "version": "custom", 
                "platform":"ANY",
                "enableVNC": true,
                "name": "this.test.is.launched.by.curl",
                "sessionTimeout": "30s"
            }
        }'`

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aerokube/moon-deploy/pull/29.
