### ISSUE TITLE
Mounting volume to browser pod

### ISSUE THREAD

**Issue by emilorol** [aerokube/moon#158]
How to mount openshift volume to browser container?

```
$ oc get pvc
NAME             STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
edge18           Bound     edge18           25Gi       RWO                           8m
ie11             Bound     ie11             25Gi       RWO                           9m
```

I tried without luck:

```
  "ie": {
    "default": "11",
        "versions": {
        "11": {
          "image": "emilorol/vnc_qemu:latest",
          "port": "4444",
          "path": "/",
          "volumes":["ie11:/images"]
        }
      }
    },
  "edge": {
    "default": "18",
        "versions": {
        "18": {
          "image": "emilorol/vnc_qemu:latest",
          "port": "4444",
          "path": "/",
          "volumes":["edge18:/images"]
        }
      }
    }
```

**Comment by emilorol** [comment]
The reasoning behind this is to use OpenShift volumes to hold the windows images for example when testing internet explorer or edge browsers.

**Comment by aandryashin** [comment]
Only hostPath volumes are supported at the moment... In my opinion it is
not good idea to use volumes at all. It is better to strip down windows
images with special utilities. For ex it is possible to create 3.5Gb
windows 7 image...

пт, 20 сент. 2019 г., 18:08 Emil Orol <notifications@github.com>:

**Comment by emilorol** [comment]
Ok, thank you for the clarification. Keep up the good work.
