### ISSUE TITLE
[serviceUser] is not an admin and does not have permissions to use extra kernel capabilities for resource

### ISSUE THREAD

**Issue by O5ten** [aerokube/moon#167]
Hello, we are trying to setup moon in a very enterprisy environment and are having trouble with permissions. That means that we are setting up moon in an already existing namespace and not allowing it to create itself in the same manner, but we are reusing `moon.yaml` from the *moon-deploy* repo. 

The service user setup to use moon does not seem to *have permissions to use extra kernel capabilities for resource* whatever that means. This happens when the pods are up in the cluster, it has a proper ingress and we are trying to run a first test. The HTTP request freezes and this error message below shows up in the moon log. 

```
2019/10/28 10:15:05 [FORBIDDEN_TO_CREATE_POD] [browsers] [IP_NUMBER] [chrome-75-0-95c905bb-21c9-474a-9b21-fc8b5907b820] [pods "chrome-75-0-95c905bb-21c9-474a-9b21-fc8b5907b820" is forbidden: user "system:serviceaccount:MY_NAMESPACE:default" is not an admin and does not have permissions to use extra kernel capabilities for resource ] [480.51s]
```

Any ideas on moving forward? 
We're not about to give cluster admin to the serviceaccount.

**Comment by vania-pooh** [comment]
@O5ten 
1) Required permissions set is listed here: https://aerokube.com/moon/latest/#_required_permissions
2) Currently Moon is always adding the following to pod manifest (needed to launch Chrome):
```
"securityContext": {
    "capabilities": {
        "add": ["SYS_ADMIN"]
    }
}
```
So adding permission for this kernel capability should help. Privileged is by default turned off and is only set when explicitly enabled in `browsers.json`: https://aerokube.com/moon/latest/#_running_browser_pods_in_privileged_mode

**Comment by O5ten** [comment]
I [read somewhere](https://kubesec.io/basics/containers-securitycontext-capabilities-add-index-sys-admin/) that the `SYS_ADMIN` capability is the equivalent of allowing root-access on the pod. I'm not entirely sure that's an acceptable demand to have of a system-user. Is there a way to avoid giving that securityContext alltogether or give more specific capabilities?

**Comment by vania-pooh** [comment]
@O5ten no, currently this stuff is hard-coded. Let's implement parameterizing this in `browsers.json`.

**Comment by O5ten** [comment]
@vania-pooh allrighty! Then i guess we'll wait for this feature before trying to move out of our current selenoid grid.

**Comment by O5ten** [comment]
@aandryashin Has this already been implemented? :o

**Comment by vania-pooh** [comment]
@O5ten yep, just merged. Images will be ready in ~10 minutes. Will need to add the following to `service.json`:
```
"kernelCaps": []
```

**Comment by vania-pooh** [comment]
@O5ten btw, Chrome without `SYS_ADMIN` capability works when `--no-sandbox` flag is passed from the test.
