### ISSUE TITLE
Moon server not seeing web driver from pod in 1.4.0 (openshift)

### ISSUE THREAD

**Issue by baudren** [aerokube/moon#181]
Hello,

I am testing the new release, 1.4.0, but am having troubles with my deployment (based on the moon.yaml in the moon-deploy repository).

I added the new service, `browsers`, as explained in the changelog. One point that I did not understand - which may be the key to the problem, was the sentence: 

> The name of the service should correspond to the value of Moon -domain-name flag (default is browsers).

what is the `-domain-name` flag? I see no mention of this value anywhere in the config files.

But overall, what happens is the pods are scheduled, and start. The moon pod sees them, and waits for the webdriver, which never arrives. I can see no error in the pod, the webdriver has started.

Log from the browser pod:
```
2020/01/21 13:35:24 [INIT] [Listening on :7070]
Waiting X server...
Logging to: /home/selenium/fluxbox.log
Waiting X server...
Waiting X server...
...
Starting ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}) on port 4444
All remote connections are allowed. Use a whitelist instead!
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

 --- x11vnc loop: 1 ---

 --- x11vnc loop: waiting for: 173

PORT=5900
```

and the log on the moon pod:
```
2020/01/21 13:32:11 [INIT] [Loading quota files from: quota]
2020/01/21 13:32:11 [INIT] [Quota configuration updated]
2020/01/21 13:32:11 [INIT] [Loading users from: users/users.htpasswd]
2020/01/21 13:32:11 [INIT] [Guest access is supported as user "browsers"]
2020/01/21 13:32:11 [INIT] [Using default Moon settings]
2020/01/21 13:32:11 [INIT] [Using image = "aerokube/moon-video-recorder:1.4.0", cpu-limit = "1", memory-limit = "1024Mi" as videoRecorder]
2020/01/21 13:32:11 [INIT] [Using image = "aerokube/defender:1.4.0", cpu-limit = "0.25", memory-limit = "128Mi" as defender]
2020/01/21 13:32:11 [INIT] [Using image = "aerokube/logger:1.4.0", cpu-limit = "0.25", memory-limit = "128Mi" as logger]
2020/01/21 13:32:11 [INIT] [S3 upload is disabled: no S3 endpoint specified]
2020/01/21 13:32:11 [INIT] [Found license {owner="Default", sessions="4"}]
2020/01/21 13:32:11 [INIT] [Pods resource quota changed to 5]
2020/01/21 13:32:11 [INIT] [Moon pods number changed to 1]
2020/01/21 13:32:11 [INIT] [Listening on :4444]
2020/01/21 13:32:20 [INIT] [Loading quota files from: quota]
2020/01/21 13:32:20 [INIT] [Quota configuration updated]
2020/01/21 13:34:16 [CREATING_POD] [browsers] [xx.xx.xx.xx] [chrome-79-0-32fc289f-dd6e-4e9d-a75d-d9300bcd301f]
2020/01/21 13:34:16 [POD_CREATED] [browsers] [xx.xx.xx.xx] [chrome-79-0-32fc289f-dd6e-4e9d-a75d-d9300bcd301f] [0.11s]
2020/01/21 13:34:16 [AWAITING_DRIVER] [browsers] [xx.xx.xx.xx] [chrome-79-0-32fc289f-dd6e-4e9d-a75d-d9300bcd301f]
```

Any idea of what's happening? Thank you in advance

**Comment by vania-pooh** [comment]
@baudren `-domain-name` flag is a command-line flag for `moon` container (could be added [here](https://github.com/aerokube/moon-deploy/blob/master/moon.yaml#L100)). Default value is `browsers`, so if your service name is `browsers` everything should work out of the box. We are mainly using the following Kubernetes feature (should work at least in Kubernetes 1.13+): https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ As stated in docs:
```
For example, given a Pod with the hostname set to “busybox-1” and the subdomain set to “default-subdomain”, and a headless Service named “default-subdomain” in the same namespace, the pod will see its own FQDN as “busybox-1.default-subdomain.my-namespace.svc.cluster-domain.example”. DNS serves an A record at that name, pointing to the Pod’s IP.
```
So `browsers` is the headless service and we automatically pass its name to pod `subdomain` field. This allows to not create a distinct Kubernetes service for every pod.

**Comment by baudren** [comment]
Oh, I see - then that may be our issue, we are running a rather old openshift version (3.11, with kubernetes 3.11), and therefore this may not be compatible with our platform. I guess we'll stay on your 1.3.9 release for the time being, thanks for the clarification!

**Comment by baudren** [comment]
I actually checked, and the DNS pod service feature you mentionned seems enabled. At least, the browser pods get created with the `subdomain` set to `browsers`, as expected. But the problem remains, that the moon pod does not see the browser pods being up (see the above logs).

Could you help me diagnose where the problem lies? Can I see in the browser pod configuration, once it's up, if it has the proper networking enabled?

Thank you in advance,

**Comment by vania-pooh** [comment]
@baudren could you try to add `ports` section (e.g. 4444) to `browsers` service similarly to shown on the image. Is seems that for Kubernetes <1.13 this is required.
![IMAGE 2020-01-29 20:47:10](https://user-images.githubusercontent.com/829320/73382425-87fb8b80-42d8-11ea-85b5-d8b325bd4077.jpg)

**Comment by aandryashin** [comment]
Please try to add these ports section to the browsers srvice:

ports:
   - name: wd
     port: 4444
     protocol: TCP
     targetPort: 4444
   - name: vnc
     port: 5900
     protocol: TCP
     targetPort: 5900

ср, 29 янв. 2020 г., 20:48 Ivan Krutov <notifications@github.com>:

**Comment by baudren** [comment]
@aandryashin Yep, that worked! The grid can now see the pods, and we can connect via VPN. Thanks a lot for your support, Best!

**Comment by vania-pooh** [comment]
@baudren will fix manifests in https://github.com/aerokube/moon-deploy/issues/63.
