### ISSUE TITLE
Browser pod hangs due to failed DNS lookup

### ISSUE THREAD

**Issue by JonnyCarlyon-SpotHero** [aerokube/moon#189]
While attempting to execute my tests against Moon I am encountering what seems to be a race condition when Moon makes a request to a new browser service before it has completed registering to the DNS, and as a result the browser pod just hangs around indefinitely afterwards.   Is there any way we can wrap this request in a retry, or have a configurable value for the expected delay between adding the DNS record and trying to consume it?

```
2020/02/10 18:27:01 [DRIVER_IS_UP] [browsers] [10.31.112.10] [chrome-75-0-2f4cdefa-86cb-4d90-9644-f77e95b9b0b6] [3.13s]
2020/02/10 18:27:01 [SESSION_CREATED] [browsers] [10.31.112.10] [chrome-75-0-2f4cdefa-86cb-4d90-9644-f77e95b9b0b6] [] [3.13s]
2020/02/10 18:27:01 [PROXY_ERROR] [unknown] [10.31.112.10, 10.31.71.197] [POST http://chrome-75-0-2f4cdefa-86cb-4d90-9644-f77e95b9b0b6.browsers:4545/session] [dial tcp: lookup chrome-75-0-2f4cdefa-86cb-4d90-9644-f77e95b9b0b6.browsers on 100.64.0.10:53: no such host]
```

**Comment by vania-pooh** [comment]
Hey, this is Kubernetes DNS caching issue. How to resolve it is described here: https://aerokube.com/moon/latest/#_browser_pods_are_freezing

**Comment by JonnyCarlyon-SpotHero** [comment]
Thanks @vania-pooh that work-around seems to have fixed the issue.  Will this work-around always be necessary or will Moon eventually have retry logic that exceeds ~5 seconds?

**Comment by aandryashin** [comment]
Actually it is not a workaround, it is fix of cluster consistency in
Kubernetes. If you wish that pod will be not available immediately after
creating you can set up cache 30, 10, or 5 seconds... Another way is to
configure coredns to do not cache negative resolves...

ср, 12 февр. 2020 г., 20:33 JonnyCarlyon-SpotHero <notifications@github.com

**Comment by JonnyCarlyon-SpotHero** [comment]
Thanks for the additional info @aandryashin, leaving DNS caching disabled within the namespace seems like the best way forward.
