### ISSUE TITLE
documentation update: installing a new license

### ISSUE THREAD

**Issue by tdensmore** [aerokube/moon#196]
It would be helpful to update the **Installing License** section of the documentation to include the fact that the license key send via email is **not base 64 encoded**. Pasting it directly into the license secret data field will result in the license not being applied to the cluster.

It would be good to mention that GKE Kubernetes will automatically update pods with the new license secret according to the value of the "secrets caching time" setting, so there is no need to restart Moon.

**Also**: please document the naming differences of secrets between the Google Marketplace version of your application and the git based install version.

**Default install**
```
licensekey                    Opaque                                1      19m
users                         Opaque                                1      19m
```
**Marketplace install**
```
moon-marketplace-licensekey   Opaque                                1      3m37s
moon-marketplace-users        Opaque                                1      3m37s
```

Also, this command:

`kubectl edit secret moon-marketplace-licensekey`

should be 

`kubectl edit secret moon-marketplace-licensekey -n moon`

since the marketplace application will create the moon namespace by default.

![image](https://user-images.githubusercontent.com/469399/76971255-562f9a00-6903-11ea-84e9-39d64186ef55.png)

There may be other differences between the marketplace version that your documentation is unaware of, so perhaps a **warning** in the documentation might guide new users to use the GitHub version for a better experience.

**Comment by vania-pooh** [comment]
Also need to check all docs whether `base64` encoding is mentioned there.
