### ISSUE TITLE
auto termination of zombie pods

### ISSUE THREAD

**Issue by ofirshtrull** [aerokube/moon#202]
Hello,
Today a found out that my automation team sometimes have 1-2 zombie pods once in a while 
these pods are not doing anything an are taking valid resources  such as nodes and licenses

is there a way to have the cluster see if there are any pods that are stuck or are alive for more then x minutes and kills them?

I am trying to avoid creating a special monitoring solution at the moment  

Thanks

**Comment by vania-pooh** [comment]
@ofirshtrull you should apply this fix: https://aerokube.com/moon/latest/#_browser_pods_are_freezing Then pods you should not have such pods anymore. Moon certainly has timeout logic, but this is reproducing because of Kubernetes bug.

**Comment by ofirshtrull** [comment]
it's already configured 

 1 ❯ kubectl get cm coredns -n kube-system -o yaml
apiVersion: v1
data:
  Corefile: |
    moon.svc.cluster.local:53 {
        errors
        kubernetes cluster.local {
          namespaces moon
        }
    }
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      upstream\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"eks.amazonaws.com/component":"coredns","k8s-app":"kube-dns"},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2020-03-03T05:58:05Z"
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
  resourceVersion: "65261"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: f34d9137-5d13-11ea-9af2-0ad111c08350

**Comment by vania-pooh** [comment]
@ofirshtrull This example config was made for namespace `moon`. If you are running everything in another namespace, then it should be changed. If you are sure - you are running Moon in correct namespace then `moon` containers logs related to frozen pod could help to diagnose:
```
$ kubectl logs moon-xxxxx -c moon -n moon 2>&1 | grep chrome-xxxxx
$ kubectl logs chrome-xxxxx -c defender -n moon
```

**Comment by ofirshtrull** [comment]
I am in the moon namespace but i have terminated the pods already
next time it happens i will send you the logs

**Comment by ofirshtrull** [comment]
@vania-pooh I had another stuck pod
here are the logs you asked for

```
❯ kubectl logs moon-7484558cfd-9kd6l -c moon -n moon 2>&1 | grep chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997

2020/03/30 04:36:49 [CREATING_POD] [browsers] [172.35.11.133] [chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997]
2020/03/30 04:36:50 [POD_CREATED] [browsers] [172.35.11.133] [chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997] [0.04s]
2020/03/30 04:36:50 [AWAITING_DRIVER] [browsers] [172.35.11.133] [chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997]
2020/03/30 04:36:52 [DRIVER_IS_UP] [browsers] [172.35.11.133] [chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997] [2.08s]
2020/03/30 04:36:52 [SESSION_CREATED] [browsers] [172.35.11.133] [chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997] [lesson-completion;user-can-complete-a-specific-lesson] [2.08s]
2020/03/30 04:36:52 [PROXY_ERROR] [unknown] [172.35.11.133] [POST http://chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997.browsers:4545/session] [dial tcp: lookup chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997.browsers on 10.100.0.10:53: no such host]
```

and ```kubectl logs chrome-65-0-5b768215-99b1-4d45-a107-fe6b64510997 -c defender -n moon```
was empty

**Comment by aandryashin** [comment]
Hello, error "no such host" occurs when dns cache is enabled, as you
mentioned dns cache is disabled in your cluster. Could you please check
that settings applied to coredns, also please check that settings in
Corefile is for moon namespace and moon is running in moon namespace...

пн, 30 мар. 2020 г., 09:58 ofir shtrull <notifications@github.com>:

**Comment by vania-pooh** [comment]
@ofirshtrull as expected this is just the same issue I mentioned before, so for some reason our fix did not apply.

**Comment by ofirshtrull** [comment]
previously I only added moon.svc.cluster.local:53
I just added after your remark 
.:53 { ready and ttl 30 }
and yes everything moon-related is running in moon namespace

**Comment by aandryashin** [comment]
Could you please check coredns logs in kube-system namespace? Are there any
errors that can cause that configuration is not applied?

пн, 30 мар. 2020 г., 12:51 ofir shtrull <notifications@github.com>:

**Comment by jshumaker** [comment]
> Moon certainly has timeout logic, but this is reproducing because of Kubernetes bug.

It sounds more like Moon has a timing bug and a lack of retries?  There was issue #130 which claims retry logic was implemented, but our own experience is that it does not retry and fails, and this alternate config is required.  Is there some technical reason Moon can not be updated to avoid this hang regardless of the coredns configuration? We'll be implementing the change, but it seems more like a workaround to a Moon bug, rather than a Kubernetes bug as claimed.

**Comment by vania-pooh** [comment]
@jshumaker what Moon version are you talking about? We added a set of fixes in latest releases.

**Comment by jshumaker** [comment]
We were on 1.7.1 and just upgraded to 1.8.1, but applied the workaround before that upgrade.

**Comment by rvvincelli** [comment]
> @ofirshtrull you should apply this fix: https://aerokube.com/moon/latest/#_browser_pods_are_freezing Then pods you should not have such pods anymore. Moon certainly has timeout logic, but this is reproducing because of Kubernetes bug.

Thank you @vania-pooh , this might have solved our zombie pods issue, which we were handling with manual pod kills in between runs, but it's basically impossible to handle in between single tests in the same run. I hope you may patch the CoreDNS configmap with the next release (perhaps it's not possible as you mention that in the documentation explictly).

Another cause for unsatisfactory pods is a cluster which is too thin. But you mention minimum requirements at installation time, at least on DigitalOcean, so the user should know.

In general I highly suggest to add such switches when launching a single test or suite:
`--timeout 120000 --browser-timeout 600000 --new-browser-wait-timeout 600000 --disable-timeout-retry --retries 1`
(details may vary according to your client, driver etc.)

**Comment by vania-pooh** [comment]
In Moon 2.0.0 we don't rely on DNS at all. So this should not reproduce.
