### ISSUE TITLE
Feature Request: Support capability to run containers without requiring fsGroup

### ISSUE THREAD

**Issue by timothyjmtan** [aerokube/moon#207]
Hi,

Following-up with my conversation with @aandryashin on the Moon Telegram group, I am raising this feature request ticket to support capability to run containers without specifying `fsGroup`.

Due to our organization's psp (pod security policy), we have a restriction where we are not allowed to mount any persistent block storage, i.e. we do not have a valid `fsGroup` id to use. As such, when attempting to launch moon containers, we are running into the following error:

`[fsGroup] Invalid Value: []int64(65545): 65534 is not an allowed group`

Could we get support for future releases so that we can choose to disable `fsGroup`?

**Comment by timothyjmtan** [comment]
@vania-pooh Will you folks be able to do a hot-fix for this first, so that we can test if it works prior to 1.5.1 release? We volunteer as tribute.

**Comment by vania-pooh** [comment]
@timothyjmtan will do and notify you here as soon as these changes are merged.

**Comment by vania-pooh** [comment]
@timothyjmtan ok, fix should be available in `aerokube/moon:latest` image and will be released in 1.5.1.

**Comment by timothyjmtan** [comment]
@vania-pooh I've tested with `aerokube/moon:latest`, works great. Thank you very much!

**Comment by vania-pooh** [comment]
@timothyjmtan ok, closing then.
