### ISSUE TITLE
Add license expiration metric to prometheus

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#211]
Could be used to monitor license expiration.

**Comment by dekhtyarev** [comment]
Hi!
Which release is expected task?

**Comment by vania-pooh** [comment]
@dekhtyarev should will be done in 1.7.2.

**Comment by dekhtyarev** [comment]
@vania-pooh 

Will 2.0.0 include this metric?
We have already missed the license renewal once.

**Comment by vania-pooh** [comment]
@dekhtyarev yes it should. But we are now also working on expiring licenses notification by email.

**Comment by vania-pooh** [comment]
Added in Moon 2.0.0. Metric is called `moon_license_expire`. https://aerokube.com/moon/latest/#monitoring-built-in-metrics
