### ISSUE TITLE
Can not connect to moons websocket when trying to use devtools

### ISSUE THREAD

**Issue by SeleniumTestAB** [aerokube/moon#215]
When trying to use URL "ws://{host}/devtools/{sessionId}/page/" the connection can not be established because of handshake error. Furthermore, i can create session when using "{host}/wd/hub" without specifying 4444 port.

**Comment by SeleniumTestAB** [comment]
Additional info is, we use openshift with k8s < 1.13 so i customized yml file from deploy-moon repository. It did create routes and service, etc.. and i can make session as stated above, but route/service for moon alone redirects to moon-ui. Is it good?

**Comment by SeleniumTestAB** [comment]
I finally solved my issue. The example yaml has problems with services, the are not separated correclty.

**Comment by vania-pooh** [comment]
@SeleniumTestAB if our `moon-openshift.yaml` has issues your suggestions could help to make it better.

**Comment by SeleniumTestAB** [comment]
@vania-pooh the services, moon-ui service and moon service should be 2 different services and 2 different routers. Otherwise openshift will think that moon is going to moon-ui even thought root is for port 4444.

Once i made those services separated the moon finally worked. Speaking about moon as app not a whole cluster/namespace

**Comment by vania-pooh** [comment]
@SeleniumTestAB thanks.
