### ISSUE TITLE
Document how Moon queuing works

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#216]
1) Describe how Moon queues works
2) Why it is important to set load balancer \ ingress timeout
3) What does `context canceled` and `CLIENT_DISCONNECTED` messages mean

**Comment by johnxy84** [comment]
Hey, just wondering was this documented anywhere? it's actually useful

**Comment by vania-pooh** [comment]
@johnxy84 see https://aerokube.com/moon/latest/#_adjusting_timeouts.

**Comment by johnxy84** [comment]
Ah, I was talking mostly about how the queueing works

**Comment by vania-pooh** [comment]
@johnxy84 queuing mainly relies on Kubernetes scheduler. Only requests for new pods on top of your resource quota limit or those who wait for upscaling to complete will wait in queue. All other pods should start immediately.

**Comment by johnxy84** [comment]
Ok, Thanks @vania-pooh
