### ISSUE TITLE
Will Moon work with AWS LocalStack S3?  I cannot get it to work.

### ISSUE THREAD

**Issue by djangofan** [aerokube/moon#218]
I am trying to test the default 4-thread Moon install , while running LocalStack locally on my Mac:

To reproduce: 

1. Clone the LocalStack Github repo and then start on your mac with `TMPDIR=/private$TMPDIR docker-compose up` .   Supposedly this should work regardless of the key/password you use since LocalStack ignores authentication.    open admin on localhost:8081
2.  once localstack is running, change its external admin port to 8081, rather than 8080  (which will conflict with Moon admin)
3.  Then, I tried to configure Moon like so:

```
data:
  service.json: |
    {
      "kernelCaps": [ "SYS_ADMIN" ],
      "s3": {
        "endpoint": "http://localhost:4572",
        "bucketName": "moon-test",
        "version": "S3v2"
      }
    }
```

Anyone ever get this working?   Moon fails to push up test results to the bucket,  nor does it create the bucket if the bucket does not already exist.   Not enough documentation for me to know what to expect here.    NOTE: AWS CLI works fine against my local S3 in LocalStack, so shouldn't it work?

**Comment by aandryashin** [comment]
I cannot get why you need docker compose? Please check this moon deployment
repository:

https://github.com/aerokube/moon-deploy

Please use moon-local.yaml for local deployment.

сб, 4 июл. 2020 г., 23:58 Jon Austen <notifications@github.com>:

**Comment by djangofan** [comment]
I should have been clearer:  I want to use docker-compose.yml for LocalStack. ( `git clone https://github.com/localstack/localstack.git` )  only, NOT for Moon.   I think this makes perfect sense in the context of my question.

**Comment by vania-pooh** [comment]
@djangofan at least this line is wrong:
```
"endpoint": "http://localhost:4572",
```
In Kubernetes everything is running in pods and every pod has its own `localhost`. That is to say when trying to upload to `localhost:4572` container doing this will try to connect to a port `4572` of the application running **inside the same pod**. One more explanation and possible solution of this problem is here: https://stackoverflow.com/questions/55164223/access-mysql-running-on-localhost-from-minikube

**Comment by djangofan** [comment]
@vania-pooh   Thank you.  I should have known.  I think I can use  `host.docker.internal`  instead of `localhost` .     Also, I noticed you recommend MinIO  in the documentation, and so I will try that instead of using LocalStack (which was/is overkill for what I am trying to do).
