### ISSUE TITLE
How to configure with Minio?

### ISSUE THREAD

**Issue by djangofan** [aerokube/moon#220]
I am wondering if I could get some quick help with configuring  moon-local.yaml with MinIO?    I don't see anything wrong with my configuration and yet it does not work and I can't locate debug messages that might give me insight.   I am hoping someone can help or spot the typo, wherever it is?   Am I limited by the free 4-thread license?

I configured moon-local.yaml  like so:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: moon
data:
  service.json: |
    {
      "kernelCaps": [ "SYS_ADMIN" ],
      "s3": {
         "endpoint": "http://172.24.0.2:9000",
         "bucketName": "moon-test",
         "version": "S3v4"
      }
    }
# host.docker.internal  or  172.24.0.2
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: moon
stringData:
  s3.accessKey: "minio"
  s3.secretKey: "minio123"
---
```

And I setup MinIO and **moon-test** bucket with this _docker-compose.yml_:

```
version: '3.7'

services:

  minio:
   image: minio/minio:latest
   container_name: minio
   ports:
      - "9000:9000"
   environment:
     MINIO_ACCESS_KEY: minio
     MINIO_SECRET_KEY: minio123
   command: server /data

  #load up data
  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minio minio123;
      /usr/bin/mc rb --force local/moon-test/;
      /usr/bin/mc mb --quiet local/moon-test/;
      /usr/bin/mc policy set public local/moon-test;
      "
```

My DesiredCapabilities are set like so,  in this case using **FireFox 52.0**:

```
DesiredCapabilities caps = new DesiredCapabilities("firefox", "52.0", Platform.LINUX);
caps.setCapability("screenResolution", "1280x1024x24");
caps.setCapability("enableVNC", true);
caps.setCapability("enableVideo", true);

```

**Comment by vania-pooh** [comment]
@djangofan 
1) You can use with 4 parallel sessions completely free and for unlimited time. If you would like to try  more - we are giving free 1-month evaluation license keys for 50 parallel sessions on our website: https://aerokube.com/moon/
2) Your configuration seems to be correct (assuming that config map and secret are mounted to `moon` container). However you can easily diagnose what is not working by printing `logger` container logs while executing some test:
```
$ kubectl logs -f chrome-xxxxxx -c logger -n moon
```
Also make sure Moon logs contain a message that S3 is enabled at all.

**Comment by djangofan** [comment]
1. Thanks.  I will try.   How do I discover the UUID associated with running my firefox tests (for that log statement)?
2. Also, when we configure **endpoint** value (above),  it is unclear to me if that endpoint is supposed to be relative to the Kubernetes cluster images OR relative to the kubernets-host??
3.  Lastly,  I do see this message in the main 'moon' pod  (using `Docker Dashboard` tool):
       **[S3 upload is disabled: no S3 access key specified]** 
    I cannot find mention of that error in any of the code in this GitHub repo.

??

**Comment by vania-pooh** [comment]
@djangofan 
1) This uuid is Selenium session ID. Can be obtained with `driver.getSessionId()` or similar method.
2) Endpoint is certainly relative to running container images.
3) That means you forgot to mount secret to Moon pod (uncomment this https://github.com/aerokube/moon-deploy/blob/master/moon.yaml#L126-L128 and https://github.com/aerokube/moon-deploy/blob/master/moon.yaml#L174-L176).

**Comment by djangofan** [comment]
I figured it out!

There were two places in the .yaml file that looked like this, which I needed to uncomment:

      - name: credentials
        secret:
          secretName: credentials

**Comment by djangofan** [comment]
The documentation did not mention needing to uncomment those extra two blocks in the .yaml

**Comment by vania-pooh** [comment]
It is documented, probably not so clear.
```
Create a Kubernetes credentials secret, mount it as a directory to Moon container and then specify path to this directory using -credentials-dir flag as shown in Credentials Secret section.
```

**Comment by djangofan** [comment]
@vania-pooh   I guess where I am stuck now is that I can't figure the correct url addres to put in my moon.yaml so that the file uploads can be pushed outside of the Kubernetes host network  to my MinIO docker container that runs on my machine also.
Any idea about that?   Ever try it?   Do I need to run Minio inside the Kubernetes cluster?

**Comment by djangofan** [comment]
I think I am getting close.  Currently I am using this URL to point to my moon server from Kubernetes:  `http://172.19.0.2:9000`  .  This is the url that the MinIO container itself says I should connect to, when examining the startup log for the Minio instance.

I am seeing log files being uploaded into MinIO but NOT YET seeing videos.   Still trying to figure out why.

note1: I am using the repo `aerokube/selenoid-container-tests`  for running the browser tests.

note2: I think that even though Kubernetes host is on the 10.*.*.* subnet,  it is able to communicate with my docker container with Minio on the 172.*.*.* subnet if I use the 172 address?

**Comment by djangofan** [comment]
Ok, I got it working.    All my above assumptions must have been correct.

Only additional note for people trying to get this to work.  I configured my capabilities like so,  in the example proejct `aerokube/selenoid-container-tests` .   Seems to have worked.  :

        DesiredCapabilities caps = new DesiredCapabilities(PROPERTIES.getBrowserName(),
             PROPERTIES.getBrowserVersion(), Platform.LINUX);
        caps.setCapability("screenResolution", "1280x1024x24");
        caps.setCapability("enableVideo", true);
        caps.setCapability("enableVNC", true);

**Comment by djangofan** [comment]
I made a PDF of instructions on how to setup MinIO
[demo-2020.pdf](https://github.com/aerokube/moon/files/4893059/demo-2020.pdf)

Probably will help someone I think.
