### ISSUE TITLE
Adding browsers.json file

### ISSUE THREAD

**Issue by xMagiciaNx** [aerokube/moon#227]
After thorough read of the documentation, I cannot find anywhere how to set new browsers, browser version, android etc. Can anyone help me resolve this issue ? Ty.

**Comment by xMagiciaNx** [comment]
Command kubectl edit configmap quota -n moon resolves the issue. Please update the documentation.

**Comment by vania-pooh** [comment]
@xMagiciaNx already in docs https://aerokube.com/moon/latest/#_how_to_update_configuration_of_a_running_moon_cluster

**Comment by xMagiciaNx** [comment]
Followed step by step guide end up in use of command
kubectl replace configmap quota --from-file=quota -n moon 
which gives you an error **--from-file error flag**

Have you ever followed the guide step by step ?

**Comment by vania-pooh** [comment]
@xMagiciaNx let me check and update docs accordingly. Probably something has changed in recent `kubectl` versions.

**Comment by xMagiciaNx** [comment]
Yes man, I thought the same one :)
Ty a million for your contribution.
