### ISSUE TITLE
Deploy moon Helm with a values.yaml

### ISSUE THREAD

**Issue by Juancarlosmartin10** [aerokube/moon#260]
Hi, 

I need to deploy moon with a config file. 

Actual deployment with helm: helm upgrade --install -n moon moon aerokube/moon
What I need: helm upgrade --install -n moon moon aerokube/moon -f values.yaml

The only way to set this variables is manually as follows:
helm upgrade --install --set=moon.enabled.resources=false -n moon moon aerokube/moon

This method is untenable for me. Thanks in advance.

Regards,

**Comment by vania-pooh** [comment]
@Juancarlosmartin10 `helm update --install -f values.yaml ....`

**Comment by soapiestwaffles** [comment]
@Juancarlosmartin10 -- Like @vania-pooh says and like you said in your post: `helm update --install -f your_values_file_name_here.yaml .... ` 

Simply create a new file with your favorite editor, put your yaml key/values that you want to set in that file, then use helm with `-f` option.

Example:

`my_values.yaml`: 
```yaml
moon:
  enabled:
    resources: false
```

run the command: `helm upgrade --install -n moon moon aerokube/moon -f my_values.yaml`

**Comment by vania-pooh** [comment]
This seems to be resolved and does not relate to Moon itself.
