### ISSUE TITLE
Ambiguity/No Examples on docs re S3 on Google Storage and lack of support for workflow identity

### ISSUE THREAD

**Issue by huang-jy** [aerokube/moon#267]
I'm using Moon on GKE (Helm install) and want to upload video from the tests onto GS. However, the docs (https://aerokube.com/moon/latest/#s3) are vague about what I need to configure for Google Storage.

I have a Google Storage bucket created in my account, and configured the service.json as described (displayed via Helm):

```
  service.json: |
    { 
      "kernelCaps": ["SYS_ADMIN"],
      "s3": {
        "endpoint": "https://storage.googleapis.com",
        "bucketName": "my-moon-bucket",
        "version": "S3v2",
        "keyPattern": "$sessionId"
      }
    }
```

But when attempting to upload the logs or video, I get this:

```
mc: <ERROR> Unable to write to one or more targets. Insufficient permissions to access this file `https://storage.googleapis.com/my-moon-bucket/chrome-89-0-61f0e62a-10b1-445f-8a36-40a8876e9492/session.log`.
```

This may be because the default service account used by the cluster doesn't have access to storage (which is intentional)

This leads me to the next question. What if I have a credentials.json file used by GCP service accounts and want to use that? (This would likely be the method if you were running in a non-google cluster and wanted to use GS and not S3)

Or, what we use Workflow Identity which requires us to use a specific Kubernetes service account? I don't see a way to (easily) specify which service account to use on the browser pods?

Happy to test or provide more information if needed.

**Comment by huang-jy** [comment]
Okay, figured out the setup.

Going through the minio site, [this page](https://docs.min.io/docs/minio-client-complete-guide.html) pointed me to [this page](https://cloud.google.com/storage/docs/migrating?hl=en#keys), which then let me figure out how to create an access/secret key which I then use in the config, without needing a credentials json.

Might be worthwhile to put this on the docs or make them clearer

**Comment by vania-pooh** [comment]
@huang-jy stuff related to service account is described here: https://aerokube.com/moon/latest/#service-account

**Comment by huang-jy** [comment]
> @huang-jy stuff related to service account is described here: https://aerokube.com/moon/latest/#service-account

That would work for installations where you're installing directly into the cluster, but if I'm installing via Helm I can't do that unless I extract and patch the chart, then install from that?

**Comment by vania-pooh** [comment]
Let's then add service account support to chart.

**Comment by huang-jy** [comment]
Thanks very much :)

**Comment by vania-pooh** [comment]
@huang-jy btw, here is the definition of our service account in chart: https://github.com/aerokube/charts/blob/master/moon/templates/moon.yaml#L2-L42 Probably it would be simpler to add permissions to this one.

**Comment by huang-jy** [comment]
Is it okay if try to patch and make a PR?

**Comment by vania-pooh** [comment]
@huang-jy you could, but let's discuss first suggested changes. You could send an example here first.

**Comment by huang-jy** [comment]
Perfect. I will work on my changes, then post them here before raising a PR

**Comment by huang-jy** [comment]
Here are my changes.

For workflow identity to work, the service account must be tagged with a specific annotation:

```
"iam.gke.io/gcp-service-account":"{gcp-sa}@{gcp-project}.iam.gserviceaccount.com"
```

So if the GCP service account is "moon-sa" in project "test-project", the annotation would be 

```
"iam.gke.io/gcp-service-account":"moon-sa@test-project.iam.gserviceaccount.com"
```

The GCP sa also requires configuring to indicate which Kubernetes service account to expect, but that's not in scope for this change.

The change I propose is simple: allow the user to optionally add annotations to the serviceaccount created by the Helm install:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.moon.serviceaccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.moon.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
```

Then in values.yaml:

```
moon:

  ....

  serviceaccount:
    annotations: {}

  ....

```

Users can override the values.yaml in the usual way

```
moon:

  ....

  serviceaccount:
    annotations:
      iam.gke.io/gcp-service-account:moon-sa@test-project.iam.gserviceaccount.com

  ....

```

And verify it shows up on the service account itself:

```
$ kubectl get serviceaccount -n moon moon -o yaml                                                   
apiVersion: v1                                                                                                                                         
kind: ServiceAccount                                                                                                                                   
metadata:                                                                                                                                              
  annotations:                                                                                                                                         
    iam.gke.io/gcp-service-account: moon-sa@test-project.iam.gserviceaccount.com                                                                       
    meta.helm.sh/release-name: moon                                                                                                                    
    meta.helm.sh/release-namespace: moon            
```

It can also be tested using gcloud builders:

(Using no annotation)
```
$ kubectl run -n moon --rm --serviceaccount=moon -it test --image gcr.io/cloud-builders/gsutil ls   
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.                                                                                                                                           
If you don't see a command prompt, try pressing enter.                                                                                                 
AccessDeniedException: 403 Caller does not have storage.buckets.list access to the Google Cloud project.                                               
Session ended, resume using 'kubectl attach test-5b87dbc985-dhnjw -c test -i -t' command when the pod is running                                       
deployment.apps "test" deleted                  
```

(Using an annotation)
```
$ kubectl run -n moon --rm --serviceaccount=moon -it test --image gcr.io/cloud-builders/gsutil ls
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
gs://bf-moon-assets/
gs://backups/
gs://wp-assets/
gs://wp-backups
Session ended, resume using 'kubectl attach test-5b87dbc985-kgggm -c test -i -t' command when the pod is running
deployment.apps "test" deleted

```

**Comment by vania-pooh** [comment]
@huang-jy please go ahead and create a PR. Don't forget to add a comment on top of your key in `values.yaml`.

**Comment by huang-jy** [comment]
PR raised https://github.com/aerokube/charts/pull/50

One note: The current chart version available on the helm repo is 1.1.4, but the Chart.yaml in the git repo shows 1.0.7, I bumped the version to 1.1.5 for this change. If that is wrong, let me know and I'll put it down to 1.0.8

**Comment by vania-pooh** [comment]
@huang-jy see my comments in your PR.

**Comment by huang-jy** [comment]
Thanks @vania-pooh I've made the changes requested

**Comment by vania-pooh** [comment]
@huang-jy merged.

**Comment by vania-pooh** [comment]
@huang-jy tagged as https://github.com/aerokube/charts/releases/tag/1.1.5.

**Comment by huang-jy** [comment]
Thank you very much. I will close this issue
