### ISSUE TITLE
[feature] Allow mounting in of configmaps/secrets into browser pods (Helm/Kubernetes)

### ISSUE THREAD

**Issue by huang-jy** [aerokube/moon#268]
I have a test that requires me to upload a file to the site I'm running the test on, then perform other actions.

Is it possible for the browser pod to mount in a conifgmap and/or secret so the test does not need to download the file(s) from an external location?

So something like this:

```
capabilities = {
    "browserName": "chrome",
    "browserVersion": "89.0",
    "enableVNC": True,
    "enableVideo": True,
    "mountConfigMap": "{name of configmap}:{mount dir}", <--
    "mountSecret": "{name of secret}:{mount dir}" <-- 
}

gridhost="moon.mydomain.com"

options = Options()
options.add_argument('--ignore-ssl-errors=yes')
options.add_argument('--ignore-certificate-errors')

driver = webdriver.Remote(
    command_executor=f"http://{gridhost}:4444/wd/hub",
    desired_capabilities=capabilities,
    options=options)

driver.do_stuff(.....)

```

This would allow me to prepare the supporting file(s) before I trigger the test, minimising the amount of time spent actually doing the test, and reducing the file size of the ensuing video recording.

This would also allow credentials to be decoupled from the test.

**Comment by vania-pooh** [comment]
This is a duplicate of #182.

**Comment by huang-jy** [comment]
Thanks. Shall I close this instead?

**Comment by vania-pooh** [comment]
@huang-jy yeah, let's do this.

**Comment by huang-jy** [comment]
Closing as dupliate
