### ISSUE TITLE
Browser pod uses default service account

### ISSUE THREAD

**Issue by sfaisalshah** [aerokube/moon#269]
Hi,

I am using custom service account in moon deployment, this service account has access to s3. 

```    
spec: 
   serviceAccountName: selenoid-moon
```
         
Problem is with the browser pod. Whenever a browser pod comes up, it uses default serviceaccount and results do not get uploaded to s3.

I am using aerokube/moon:1.7.0, is there any other required configuration ?

**Comment by vania-pooh** [comment]
@sfaisalshah Moon container has `-service-account-name` flag described here: https://aerokube.com/moon/latest/#cli-flags-moon An example of usage is e.g. here: https://github.com/aerokube/charts/blob/master/moon/templates/moon.yaml#L172

**Comment by sfaisalshah** [comment]
Worked. Thanks.
