### ISSUE TITLE
Change type of service moon-browsers (Kubernetes)

### ISSUE THREAD

**Issue by Juancarlosmartin10** [aerokube/moon#274]
Hi, I deployed moon on Kubernetes with helm and a values.yaml edit (Original get from ** helm show values aerokube/moon **).

I need to change the type of svc **moon-browsers** to NodePort, ads default on ClusterIP, but I din`t see this on values.yaml

![image](https://user-images.githubusercontent.com/33909840/119694146-42f45480-be4d-11eb-9f3b-afa33877b668.png)

Thanks in advance.

**Comment by vania-pooh** [comment]
@Juancarlosmartin10 I would then use [moon-deploy](https://github.com/aerokube/moon-deploy) instead and edit everything as needed.

**Comment by Juancarlosmartin10** [comment]
Ok, thanks.
