### ISSUE TITLE
Remote WebDriver Auth?

### ISSUE THREAD

**Issue by huang-jy** [aerokube/moon#279]
Not sure which repo to put this on, so apologies if this isn't the right one

But I've been able to install and use Moon for a bit now, but unless I'm missing something, it seems that the Helm deploy config makes a public-available loadbalancer which seemingly does not require any authentication to start a Selenium session, meaning anyone could abuse it if they found the dns name/IP and port:

```
driver = webdriver.Remote(
    command_executor=f"http://{moon_host}:4444/wd/hub",
    desired_capabilities=capabilities,
    options=options)
```

Someone could maliciously repeatedly lock up all available agents in long-running sessions as a result.

Even if you password protect the UI, it's not much help if the loadbalancer is open.

Is there a way to protect or require auth when using the remote webdriver?

A "sorta" workaround is making the loadbalancer a ClusterIP and triggering the selenium sessions from within the cluster, but then you stop legitimate external selenium requests.

**Comment by vania-pooh** [comment]
@huang-jy yes, by default Moon comes configured with so-called `guest quota`, i.e. unauthenticated access. However you can create additional users and disable guest quota completely. You start by adding a user (https://aerokube.com/moon/latest/#_users_list) and then create respective `username.json` file in quota. Guest quota is configured with `-guest-user` flag (https://aerokube.com/moon/latest/#browsers-list-guest-quota). Default value is `browsers` but if you change it to the value with no JSON quota, then you will not be able to access Moon.

**Comment by huang-jy** [comment]
How would I "authenticate" to Moon from the webdriver? Bearing in mind, I might need to authenticate to the host I'm testing via Moon so I would need to separate authenticating with Moon and authenticating with the host I need Moon to connect to.

Thanks for mentioning the quotas and browsers list. If I can get the user auth to work, I can set Moon up to only allow specific browsers and browser versions to specific users.

**Comment by huang-jy** [comment]
Ah, figured it out:

```
driver = webdriver.Remote(
    command_executor=f"http://{user}:{pw}@{gridhost}:4444/wd/hub",
    desired_capabilities=capabilities,
    options=options)
```

**Comment by vania-pooh** [comment]
@huang-jy correct, Selenium clients only support basic HTTP auth.

**Comment by huang-jy** [comment]
That now works, I'll test with some more users and different browsers, but I'll close the issue now.
