### ISSUE TITLE
Feature request: Ability to set default nodeSelector for all of Moon

### ISSUE THREAD

**Issue by soapiestwaffles** [aerokube/moon#283]
Hello,

We are currently running Moon in a cluster with mixed architecture: linux amd64 and arm64. Setting the `moon.nodeSelector` only sets the nodeSelector for the Moon pod (ui/api) and not any subsequent pods created by Moon. To go around this, I had to add a `nodeSelector` to every single browser defined in the values file. Also, it seems that the playwright urls don't work properly as well because they do not get assigned to the proper arch. 

If there isn't already a way to assign a sort of global `nodeSelector` for Moon, could one be added so that doesn't have to be so manual?

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aerokube/charts/pull/59. Already available in unstable chart. Will be available during the next days in stable chart with Moon 1.9.1 release.
