### ISSUE TITLE
Parallel execution quota misleading info

### ISSUE THREAD

**Issue by tmytlovych-perfectial** [aerokube/moon#289]
Hi
We have launched a trial moon with 10 available parallel sessions.
But we cannot reach more than 5 parallel browser sessions. VNC and video recording are turned off.
And on selenoid-ui, we can see 5+5, 4+5.

Like in the screen we have 4 parallel sessions but in the quota, there are 4 + 4. What does this mean? And how to get 10 parallel sessions of ten available?

![image](https://user-images.githubusercontent.com/62434557/134527259-ff239e5d-19aa-4e75-890b-176bc0413747.png)

**Comment by vania-pooh** [comment]
@tmytlovych-perfectial 4 pods are running, 4 pods are started. You should be able to start 2 more pods.

**Comment by aandryashin** [comment]
Please try to lost pods in namespace moon to see if there are pods in
pending state:

kubectl get po -n moon

If so, please check resources in the cluster, every browser pod requires 1
cpu and 1 Gi ram.

чт, 23 сент. 2021 г., 20:17 Ivan Krutov ***@***.***>:

**Comment by tmytlovych-perfectial** [comment]
Understood, thanks
