### ISSUE TITLE
InvalidArgumentError for clickAt

### ISSUE THREAD

**Issue by Firaenix** [aerokube/moon#298]
Hi,

I have been getting an error when I use clickAt with selenium-webdriver (nodejs) when pointing at the Moon webdriver.

```Error 'InvalidArgumentError' on command 'clickAt' 'css=canvas': invalid argument from invalid argument: 'x' must be an int (Session info: chrome=86.0.4240.75)```

If I use a local webdriver, I don't have such an error.
the code is as follows:

```
let x = Number(c.target.split(",").shift());
let y = Number(c.target.split(",").pop())
return this.driver
  .actions({ bridge: true })
  .move({ origin: element, x: x, y: y, duration: 350 })
  .click()
  .perform();
```

Am I missing something?

Thanks

**Comment by vania-pooh** [comment]
@Firaenix I would first of all check that you have a recent version of `selenium-webdriver` library.

**Comment by Firaenix** [comment]
I'm currently using version 4.0.16 which does seem to be latest

**Comment by vania-pooh** [comment]
@Firaenix in fact Moon is proxying all operations except session creation directly to respective webdriver binary. So if you take just the same Chromedriver `86.0.4240.22` and Chrome `86.0.4240.75` you will get the same error.

**Comment by Firaenix** [comment]
Alright, I'll give that a go. Thanks for the heads up

**Comment by Firaenix** [comment]
My apologies, my application code was incorrect, I had a typo. I will close the issue, thanks for your help.
