### ISSUE TITLE
Not able to start MS Edge in Moon on OpenShift

### ISSUE THREAD

**Issue by MrZeeEs** [aerokube/moon#305]
When I try to start MS Edge 97.0 in Moon, I get following error:

***
Waiting X server...
Logging to: /dev/null
Waiting X server...
Waiting X server...
Starting MSEdgeDriver 97.0.1072.8 (b634a73958e968f4dbf082c06c4610fa1e297aec) on port 4444
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.

 --- x11vnc loop: 1 ---

MSEdgeDriver was started successfully.
 --- x11vnc loop: waiting for: 105

PORT=5900
[1643279195.223][SEVERE]: GetCanonicalHostName Error hostname: microsoftedge-97-0-554130a7-4aa8-44d3-9692-499ef94035de
[1643279195.223][SEVERE]: Unable find match for host: moon.apps.ceokdt401.server.XYZ
***

We are running on Openshift OKD 4.6

Other browsers such as Chrome, FF or Opera start without any problem.

This the entry from browsers.json:

"MicrosoftEdge": {
        "default": "97.0",
        "versions": {
          "97.0": {
            "image": "celimregp401.server.XYZ:123/docker-hub/browsers/edge:97.0",
            "port": "4444",
             "env": [
            "HTTP_PROXY=http://someIP.135:8080",
            "HTTPS_PROXY=http://someIP.135:8080",
            "NO_PROXY=.cetin,.cluster.local,.svc,10.0.0.0/16,10.220.0.0/17,10.220.128.0/17,127.0.0.1,172.29.158.128/25"
            ]
          } 

Could you please help?

**Comment by vania-pooh** [comment]
@MrZeeEs this is because recent Chromedriver (starting from version 92.0 so far as can remember) and derived drivers (e.g. edgedriver) require Host header to be equal to the same host where it's running. This is a security measure. Recent Moon versions (1.9.0+) should set this header for you automatically. What is your Moon version?

**Comment by MrZeeEs** [comment]
Hi, thanks!
We have version from 12th May 2021:
![image](https://user-images.githubusercontent.com/97615346/151510254-ee1e3c90-bb48-48a5-9188-d418e288cbbc.png)

**Comment by vania-pooh** [comment]
@MrZeeEs Moon 1.9.0, where this was fixed, was released in June 2021. https://github.com/aerokube/moon/releases/tag/1.9.0

**Comment by vania-pooh** [comment]
This is now also fixed in Moon 2.0.0.
