### ISSUE TITLE
Ability to set global tolerations to browsers pods

### ISSUE THREAD

**Issue by agrrh** [aerokube/moon#309]
Please see:

#122
>Add Toleration to Browsers List

#284
>Ability to set global nodeSelector to browsers pods

Could `tolerations` functionality be set globally, too?

**Comment by vania-pooh** [comment]
@agrrh this is going to be released in Moon 2 during next weeks.

**Comment by Boniker** [comment]
@vania-pooh Any updates? +1

**Comment by vania-pooh** [comment]
Yes this is available in Moon 2, see: https://aerokube.com/moon/latest/#browsers-set-tolerations
