### ISSUE TITLE
Interact with existing session?

### ISSUE THREAD

**Issue by huang-jy** [aerokube/moon#310]
Hi there, I've been looking for a way to download the results of tests from a moon session pod so they can be made available to the CI/CD pipeline. I found the documentation here: https://aerokube.com/moon/latest/#_accessing_files_downloaded_with_browser

But I have a question. 

During the process of running the test, the local terminal sends off the request to moon, and moon then runs the test, saving the files locally to the pod, and accessible via the URLs specified in the documentation. My question is this.: In order to access those files, I need to end the current python session which triggered the moon pod, go and download the results from the URLs, then reconnect to the session and terminate it cleanly. Yes, I can wait for the timeout, but I'd rather have testers cleanup tests as they go as a matter of habit.

Assuming I can note the session ID, how do I reconnect with the session so I can terminate it properly?

**Comment by vania-pooh** [comment]
@huang-jy Moon is fully W3C Webdriver protocol compatible. So every action like opening a new session, opening URL in browser, downloading a file and terminating a session is a separate HTTP request. To [delete a session](https://www.w3.org/TR/webdriver/#delete-session) you can send an HTTP request like this:

```
DELETE /wd/hub/session/<id> # /wd/hub is actually just a constant prefix
```

Usually your Selenium client does this when you do `driver.quit()`.

**Comment by huang-jy** [comment]
> Usually your Selenium client does this when you do `driver.quit()`.

Yes, and I am particular about making sure both the session and the driver call `.quit()` before ending, but in order to download the files from the session, I need it to stay up after I close out (without closing the session)

Thanks for the details about the delete call -- I couldn't find mention of it on the documentation and didn't think of checking the actual webdriver documentation.
