### ISSUE TITLE
moon with playwright: why all sessions lanched in parellel are not recorded to s3 bucket ?

### ISSUE THREAD

**Issue by MohamedBenighil** [aerokube/moon#352]
Hello,

I deployed moon2, using helm, on my k8s Cluster. When i launch 2 tests in parallel, i got just one  1/2 video on my bucket ?

i am using c# with playwright

have you an idea please ? 

Thank you in advance for your help

**Comment by vania-pooh** [comment]
@MohamedBenighil are you using Playwright browser contexts or separate connections to Moon? For Moon every connection to ws:// endpoint is a separate browser session being recorded independently, whereas browser contexts are considered the same session.
