### ISSUE TITLE
[Python] "TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'" 

### ISSUE THREAD

**Issue by huang-jy** [aerokube/moon#358]
Usage of the `desired_capabilities` in Python is throwing deprecation warnings:

```
DeprecationWarning: desired_capabilities has been deprecated, please pass in an Options object with options kwarg
  driver = webdriver.Remote(
```

Would it be worth updating the documentation and examples in the UI?

Also, when I say "examples", I am referring to this:

![image](https://user-images.githubusercontent.com/2756283/207278249-ebd755d6-eb26-4e16-8ff4-c4e4495b505c.png)

**Comment by vania-pooh** [comment]
@huang-jy any ideas about possible updated code?

**Comment by huang-jy** [comment]
Not yet, but I'll share once I get a chance to figure it out

**Comment by vania-pooh** [comment]
@huang-jy the problem is that you have to use separate classes like ChromeOptions, FirefoxOptions and so on. It is more complicated to provide such examples in the UI.

**Comment by huang-jy** [comment]
Agreed, but since the user is already picking the browser type on the left (the dropdown), that part should be obtainable from the user's actions.

Additionally, you don't need to provide examples for everything, you can give a basic example like in the UI already, and point the user to the documentation on the relevant browser options (ChromeOptions, FirefoxOptions as you pointed out)  to fill in the rest.

**Comment by huang-jy** [comment]
Just picking this up again after having an opportunity to dig into this a bit more. I have some examples which we can use:

Previously:

```
capabilities = {
    "browserName": "chrome",
    "browserVersion": "106.0",
    "moon:options": {
        "enableVNC": True,
        "enableVideo": True,
        "name": f"SetupUser",
        "sessionTimeout": "5m"
    }
}

driver = webdriver.Remote(
    command_executor=f"https://user:pass@{gridhost}/wd/hub",
    desired_capabilities=capabilities)
```

This will now error with 

`TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'`

Due to changes with Selenium (Question was asked on SO: https://stackoverflow.com/questions/76430192/getting-typeerror-webdriver-init-got-an-unexpected-keyword-argument-desi, referenced change at Selenium HQ here: https://github.com/SeleniumHQ/selenium/commit/9f5801c82fb3be3d5850707c46c3f8176e3ccd8e)

Instead, you need to use the `Options` object (`selenium.webdriver.chrome.options`, `selenium.webdriver.firefox.options` or similar)

```
from selenium.webdriver.chrome.options import Options

...

moon_options={
        "enableVNC": True,
        "enableVideo": True,
        "name": f"SetupUser",
        "sessionTimeout": "5m"
    }

options=ChromeOptions()
options.set_capability("browserName", "chrome")
options.set_capability("browserVersion","106.0")
options.set_capability("moon:options",moon_options)

driver = webdriver.Remote(
    command_executor=f"https://user:pass@{gridhost}/wd/hub",
    options=options)

```

**Comment by SanthoshKumar3624** [comment]
if i am planning to automate with WinAppDriver what should i use in place of  **from selenium.webdriver.chrome.options import Options**
