### ISSUE TITLE
[Moon UI] - new type of Dashboard (v.2.4.0) doesn't load if URL has basic auth credentials inside of it

### ISSUE THREAD

**Issue by aryazantsev** [aerokube/moon#362]
Hi all,

We use new Moon UI dashboard that was released in v2.4.0 and mentioned a bug there.

Our Moon is under basic auth so for accessing dashboard I use a URL with preformatted credentials inside of it. Here are some details:

- Link format: https://moon-basic-auth-user:moon-password@my.moon.url/ui/
What I see when page is loaded (data is not loaded):
![image](https://user-images.githubusercontent.com/26273409/209646714-29710994-197e-4c49-9b61-fcac0c54f50e.png)
 
Old version works great (same URL but with different ending for old version of UI)
![image](https://user-images.githubusercontent.com/26273409/209646855-74ae41c7-806d-4633-97fd-9fc4ed2923fe.png)

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aerokube/moon2/pull/186.
