### ISSUE TITLE
Moon Browses Stucks and Can not be deleted

### ISSUE THREAD

**Issue by algassimbarry** [aerokube/moon#367]
Hi Team,
i am having an issue on moon as some browsers are stucks and i can not delete them.
Usually when i delete the application and recreate it, it use to solve the issue, but this time it haven't.
by the way the application is deployed on Kubernetes (with Gitlab and Argocd).
There is nothing in the logs that can help to investigate it.
Did you faced this issue before ?
could you please help and advise?
Thanks in advance.

**Comment by algassimbarry** [comment]
Hello again, 
Just to add some infprmations that i catched in the logs, my moon container keep restarting when these logs appears :

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
E0120 13:16:17.470211       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 61 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x130e7a0?, 0x20abf60})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x130e7a0, 0x20abf60})
        /opt/hostedtoolcache/go/1.19.5/x64/src/runtime/panic.go:884 +0x212
main.startLicenseController.func5({0x1465040?, 0xc0001f7e00?}, {0x1465040?, 0xc0001f7e00?})
        /home/runner/work/moon2/moon2/cmd/moon/license_controller.go:265 +0x3c7
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/shared_informer.go:785 +0xf7
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x10000000000?)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000163f38?, {0x16ff860, 0xc0002540f0}, 0x1, 0xc0002a8060)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000163fd0?, 0x3b9aca00, 0x0, 0x1b?, 0xc000163f88?)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0001d8400?)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:71 +0x85
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11d9ba7]

goroutine 61 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:55 +0xd7
panic({0x130e7a0, 0x20abf60})
        /opt/hostedtoolcache/go/1.19.5/x64/src/runtime/panic.go:884 +0x212
main.startLicenseController.func5({0x1465040?, 0xc0001f7e00?}, {0x1465040?, 0xc0001f7e00?})
        /home/runner/work/moon2/moon2/cmd/moon/license_controller.go:265 +0x3c7
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/shared_informer.go:785 +0xf7
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x10000000000?)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000163f38?, {0x16ff860, 0xc0002540f0}, 0x1, 0xc0002a8060)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000163fd0?, 0x3b9aca00, 0x0, 0x1b?, 0xc000163f88?)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0001d8400?)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:71 +0x85
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

**Comment by algassimbarry** [comment]
Hello Team,
Any update on this please?
I have identified this in my logs as well:

2023/01/30 15:57:09 [INIT] [Listening on :8080]
2023/01/30 16:07:07 ****[STATUS_ERROR] [get status: Get "http://localhost:4444/status": dial tcp [::1]:4444: connect: connection**** refused]
2023/01/30 15:57:07 [INIT] [Listening on :8080]

Thank you in advance.

**Comment by vania-pooh** [comment]
@algassimbarry how about just updating everything to Moon 2.x? Your log is for Moon 1.0.

**Comment by algassimbarry** [comment]
@vania-pooh i am confuse, because i am actually using moon2 chart.

**Comment by vania-pooh** [comment]
@algassimbarry in Moon 2.x we completely changed logging output. Any output with square brackets is only present in Moon 1.x. How are you actually installing Moon 2?

**Comment by algassimbarry** [comment]
@vania-pooh i am using this chart here: https://github.com/aerokube/charts/tree/master/moon2 .

**Comment by algassimbarry** [comment]
@vania-pooh  is that the correct one please?
i tried to go through my chart but cannot find where it stated thst is moon 1

**Comment by algassimbarry** [comment]
@vania-pooh In the log, there are some part where "moon2" is mentionned ( you can check on the log i sent above as well )

![image](https://user-images.githubusercontent.com/63313560/215796899-cd9ee2da-5a3b-492b-bed7-b81d1d3b8869.png)

**Comment by vania-pooh** [comment]
@algassimbarry ok, we'll check on our side.

**Comment by algassimbarry** [comment]
Thank you!

**Comment by vania-pooh** [comment]
This was released as Moon 2.4.4.

**Comment by algassimbarry** [comment]
Perfect, i will update with this tag
thanks a lot!
@vania-pooh any advise regarding the stucks browsers please?
i am notable to get ride of them even if i delete the application and recreate it. They will appear again!

**Comment by vania-pooh** [comment]
@algassimbarry take a look at `defender` container logs for stuck browser pods.
```
$ kubectl logs -lapp=moon -c defender -n moon
```

**Comment by algassimbarry** [comment]
Thank you!
