### ISSUE TITLE
Unable to run concurrent sessions in Selenoid UI

### ISSUE THREAD

**Issue by anjithk99hallmark** [aerokube/moon#370]
Hi Team,

We have created Kubernetes cluster and deployed moon from the official image https://github.com/aerokube/moon-deploy.git, now when we are trying to run multiple sessions of 4 which is supported. We were able to run only one and remaining pods are going in waiting stage. Could please someone help here. Thanks
![Pending State](https://user-images.githubusercontent.com/124166768/216064273-da72b9e6-e405-4899-a08d-2a511587bc44.JPG)
![Moon Issue](https://user-images.githubusercontent.com/124166768/216064283-d3af500a-cad6-4c3d-b1bc-0513dccfb5fb.JPG)

**Comment by vania-pooh** [comment]
@anjithk99hallmark probably you just run out of computing resources. Describe pod in Pending state to get the reason:

```
$ kubectl describe po chrome-XXXXX -n moon
```

**Comment by anjithk99hallmark** [comment]
Hi @vania-pooh  Thanks for the confirmation. Forgot to inform you that the case is closed
