### ISSUE TITLE
Playwright error: Unknown engine "internal:testid"

### ISSUE THREAD

**Issue by anupamck** [aerokube/moon#376]
We use a custom test data attribute during testing, which we configure using Playwright's inbuilt `testIdAttribute` key in the config file. See https://playwright.dev/docs/api/class-framelocator#frame-locator-get-by-test-id 

When I run my Playwright tests using the latest moon version (1.28.1 as of this date), the tests work fine. But when I try using an older Moon Playwright image (1.27.1, 1.26.1, 1.25.1 etc.) I receive the following error: 

`locator.click: Unknown engine "internal:testid" while parsing selector internal:testid=[data-object-name="FilterRadioButton-application-option-0"s]`

Using an older Moon Playwright image is important for us to test compatibility with older browser versions. 

I start the tests on Moon using the following endpoint
```wsEndpoint: `wss://moon.infra.bitgrip.berlin/playwright/${BROWSER}/playwright-${PLAYWRIGHT_IMAGE_MOON}?headless=false`,```

I could reproduce this issue with both Chrome and Firefox as browsers.

**Comment by vania-pooh** [comment]
@anupamck at least on Playwright documentation page they note that this was implemented in Playwright 1.27.

**Comment by anupamck** [comment]
@vania-pooh - Thank you. I guess it's mostly an issue with the Playwright version then. I will close this ticket. 

Btw, the moon Playwright images seem a little outdated? The latest image, 1.28.1, dates back to Nov 2022 release from Playwright.

**Comment by vania-pooh** [comment]
@anupamck in fact we automated build for Playwright images and all recent versions are available. We forgot to update HTML document.  https://quay.io/repository/playwright/chromium?tab=tags

**Comment by anupamck** [comment]
Great job! Thank you. Perhaps the update to the HTML doc should be automated too :D
