### ISSUE TITLE
Moon is loosing payed license (falling back to default license)

### ISSUE THREAD

**Issue by whrostre** [aerokube/moon#386]
Hello,
there is an issue that moon is loosing the license from time to time, or is not able to acquire it. Cause of this it's only possible to use 4 parallel sessions, because moon is falling back to the default free license. 

In the logs I have only found following message:
W0725 15:23:30.438459       1 reflector.go:442] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: watch of *v1.License ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

Our current k8s version is 1.23

**Comment by vania-pooh** [comment]
@whrostre this seems to be an issue in Kubernetes cluster side. Make sure load balancer is not closing watch connections explicitly.
