### ISSUE TITLE
Not able to download the file in Moon browser

### ISSUE THREAD

**Issue by vidushi283** [aerokube/moon#406]
We need to download the file from ui as part of test .
When button is clicked , instead of downloading the file It opens a dialog box/popup as below
![image](https://github.com/aerokube/moon/assets/134620285/8c907562-45c0-4035-a4a6-3be8b231a22a)

ChromeOptions are set as below ( using Selenium+C#)

**ChromeOptions.AddUserProfilePreference("download.default_directory", "/home/selenium/Downloads");**

Have tried setting the default directory as below as well after reading the moon docs.
**ChromeOptions.AddUserProfilePreference("download.default_directory", "/home/user/Downloads");**

But nothing worked for us .

**Comment by vania-pooh** [comment]
@vidushi283 did you try prefs from this answers? https://stackoverflow.com/questions/46937319/how-to-use-chrome-webdriver-in-selenium-to-download-files-in-python

**Comment by vidushi283** [comment]
> @vidushi283 did you try prefs from this answers? https://stackoverflow.com/questions/46937319/how-to-use-chrome-webdriver-in-selenium-to-download-files-in-python

@vania-pooh  
Currently I have set 
**ChromeOptions.AddUserProfilePreference("download.default_directory", "/home/selenium/Downloads");
ChromeOptions.AddUserProfilePreference("download.prompt_for_download": False,);**

with same pref , file is downloaded on moon instance on windows but gives the prompt when test is running on moon instance  on AWS EKS

**Comment by vania-pooh** [comment]
@vidushi283 are browser versions the same in both cases?

**Comment by vidushi283** [comment]
@vania-pooh  Working fine . it seems middle ware was the culprit. I am using testkube as my test execution tool and it pulls the image of my code from ECR repository . It seems it was not pulling the latest image which has these changes for download

Thanks

**Comment by vania-pooh** [comment]
@vidushi283 ok, closing then.

**Comment by Deepak217** [comment]
Hi @vidushi283 @vania-pooh I am facing similar issue. 
When I run test case which download a file. It works fine when moon instance is running on windows but a pop up to download file appears when moon instance running on Jenkins.
using this snippet
`prefs.put("download.default_directory",
                System.getProperty("project.build.directory") + File.separator + "target");
        prefs.put("download.prompt_for_download", false);`

Chrome version :123

Can you please help me in resolving this issue.
![image](https://github.com/aerokube/moon/assets/35289113/816d5f15-b975-41bc-bc7a-d906444ca722)
