### ISSUE TITLE
Sessions don't start - no such config: "default"

### ISSUE THREAD

**Issue by Brainpitcher** [aerokube/moon#407]
Hi there! i have installed chart 2.6.0 everything went smoothly, but when i try to start session from ui or with curl in cli, i am getting this kind of stuff **launching chrome browser: http response: {"value":{"error":"session not created","message":"internal error"}}**
in deployments logs i see **moon2-dev-8588b689fc-w7fsn: moon: no such config: "default"**
i checked  configs in crds and everything is there a Browser set and Config. 
Can you provide me some help or another way of troubleshooting of this problem?

**Comment by vania-pooh** [comment]
@Brainpitcher did you do a clean installation or an upgrade of existing Moon version?

**Comment by Brainpitcher** [comment]
> @Brainpitcher did you do a clean installation or an upgrade of existing Moon version?

Hi there! it's my fault, i forgot to redeploy crds. The issue should be closed
