### ISSUE TITLE
Slow down of tests - Debugging

### ISSUE THREAD

**Issue by whrostre** [aerokube/moon#422]
Hello, 

since a few weeks we have a strange slow down of our Selenium tests on moon. Several test execution steps take much longer than before e.g. opening the browser, clicking on elements etc. The time increase ranges from a second to several seconds. 

We have already ruled out a few things:

- We don't expect that the test object is the problem. (Locally we couldn't see any time increase)
- There was also no update with Selenium or moon. 
- Memory and cpu usage of the pods seem to be also ok. 
- There also seems to be no network issue. 

Do you have any suggestions to better debug such an issue? I would like to determine where the additional time is used. So basically during test x moon communication or the real execution in the test pod.

**Comment by vania-pooh** [comment]
@whrostre make sure you have all required firewall rules to static resources: styles, scripts, images and so on. Some pages could be loading such files from third-party resources and this could slow down things.

**Comment by whrostre** [comment]
> @whrostre make sure you have all required firewall rules to static resources: styles, scripts, images and so on. Some pages could be loading such files from third-party resources and this could slow down things.

Thanks for the hint, but we already ruled out that the webpage we are testing is the issue. Since just opening the browser takes more time than before, without loading a webpage

**Comment by vania-pooh** [comment]
@whrostre in that case I would check browser pods with `kubectl describe po chrome-XXXX -n moon`. Investigate this output and check how much time it takes to schedule the pod, to pull browser images and so on. Moon basically just creates a pod and waits for it to switch to `Running` state.

**Comment by whrostre** [comment]
Thank you. We fixed the problem with adding resources.
