### ISSUE TITLE
Unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by whrostre** [aerokube/moon#425]
Hi, 
we are currently experiencing page crashes on moon pods from time to time. 

```
Caused by: org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
```
The issue occurs from time to time and not specific to a certain test.
We found some entries about storage issues that can result to this:
https://github.com/elgalu/docker-selenium/issues/20
https://stackoverflow.com/questions/72562123/selenium-session-deleted-because-of-page-crash-from-tab-crashed

Are you aware of such an issue? Any advice maybe?

**Comment by whrostre** [comment]
Hi, 
this issue is getting bigger and more tests are affected. 
We are getting now various kinds of errors. 

`Caused by: NoSuchSessionException: invalid session id`
`Caused by: WebDriverException: unknown error: cannot determine loading status`

**Comment by vania-pooh** [comment]
@whrostre from time to time crashes are usually caused by the lack of memory for Moon browser pods. Try to add more memory in Moon settings.
