### ISSUE TITLE
Unable to record test execution video and upload on S3 for moon2.

### ISSUE THREAD

**Issue by nehagoel2712** [aerokube/moon#431]
In our automation solution we are using Selenium4, C#, specflow, moon. And moon capabilities are like this:

```
_moonOptions = new Dictionary<string, object>
{
	{ "enableVNC", true },
	{ "name", testName },
	{ "enableVideo", true },
	{"videoRetentionPeriod","24h" }
};

ChromeOptions copt = new ChromeOptions();
copt.AddAdditionalOption("moon:options", _moonOptions);
new RemoteWebDriver(new Uri(_remoteServerUri), copt.ToCapabilities(), TimeSpan.FromSeconds(Settings.Timeout));
```

we referred [this](https://aerokube.com/moon/latest/#video-recording) to setup our storage and executed following commands:
```
helm upgrade --install --set=configs.default.storage.accessKey="<Testkey>" -n moon moon aerokube/moon2
helm upgrade --install --set=configs.default.storage.secretKey="<TestSecret>" -n moon moon aerokube/moon2
helm upgrade --install --set=configs.default.storage.endpoint="<storageEndpointfor S3>" -n moon moon aerokube/moon2
helm upgrade --install --set=configs.default.storage.bucket="<Test bucket name>" -n moon moon aerokube/moon2
helm upgrade --install --set=configs.default.storage.filename="PocVideo" -n moon moon aerokube/moon2
```

After all this setup, when the test was executed, the video didn't record and was not uploaded to S3.

**Comment by aandryashin** [comment]
Please chech that values was applied, you can simple edit your config with:

kubectl edit config default -n moon

пт, 13 сент. 2024 г., 19:00 nehagoel2712 ***@***.***>:

**Comment by nehagoel2712** [comment]
The editing config worked, and I am now able to upload videos on the s3 bucket.

But it seems that upload takes place in all cases (test case either pass or fail). Is there any way to capture/upload video to S3 only when test case fails?

**Comment by vania-pooh** [comment]
@nehagoel2712 Moon does not know about tests and certainly whether test case passed or failed. Our recommendation is to enable video recording only when rerunning failed test cases.
