### ISSUE TITLE
Video uploading does not work

### ISSUE THREAD

**Issue by akhursevich** [aerokube/moon#47]
Environment: Kubernetes on AWS + Amazon S3. Everything configured according to moon documentation, moon logs do not contain any error messages.

Chrome:
Running tests with enableVideo results in creation of new folrders in S3 with selenium logs only. 
<img width="1117" alt="screen shot 2018-08-15 at 10 14 44 am" src="https://user-images.githubusercontent.com/1182755/44136075-10947cd0-a074-11e8-979d-dbbe82745200.png">

Firefox:
Firefox produces some default .mp4 files wth 1mb size regardless of test session time and it looks like video is broken, not ablt to play via Quicktime or VLC.
<img width="1115" alt="screen shot 2018-08-15 at 10 16 13 am" src="https://user-images.githubusercontent.com/1182755/44136140-48239e9c-a074-11e8-8277-331247d317f5.png">

Also, strange behavior when enableVideo=true for FF and I'm trying to redefine videoFrameRate - it applies neither a string nor int value, returning an exception:
```
org.openqa.selenium.WebDriverException: parse request: json: cannot unmarshal number into Go struct field caps.videoFrameRate of type string 
```
or
```
org.openqa.selenium.WebDriverException: json: cannot unmarshal string into Go struct field Caps.videoFrameRate of type uint16 
```
So the only option to leave this value as default.

**Comment by vania-pooh** [comment]
++ add documentation about existing capabilities

**Comment by ArunaBalasubramanian** [comment]
@hursevich Is the below endpoint correct to establish the connection with AWS cloud to upload files onto S3?

```json 
      "s3": {
        "endpoint": "http://s3.amazonaws.com",
        "bucketName": "moon-storage",
        "version": "S3v2"
      }
```
I'm unable to connect to AWS with above set up. 
Please note that my organisation has set up MFA for account access.

**Comment by vania-pooh** [comment]
@ArunaBalasubramanian all the endpoints are here: https://docs.aws.amazon.com/general/latest/gr/rande.html
Should be something like this:
```
      "s3": {
        "endpoint": "https://s3.us-east-2.amazonaws.com",
        "bucketName": "moon-storage",
        "version": "S3v4"
      }
```
