### ISSUE TITLE
Pods for sessions that failed to start are not removed

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#52]
Something related to timeout timer.

**Comment by ghostcky** [comment]
After some completed tests I`ve had 3 suspended session and only 2 test with error.
Sequence:

- 1st and 3nd: _Suspend for Remote driver initialization_

> init org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

- 2nd: _Suspend for web form filling after Remote driver initialization_

> [43:82:0903/141151.693261:ERROR:zygote_host_impl_linux.cc(270)] Failed to adjust OOM score of renderer with pid 528: Permission denied (13)

Stack: 

- Java 8
- Spring 4
- Selenium 3.6.0
- Custom Selenoid container with Chrome 68.0 (Installed CryptoPro CSP)
- Chrome extension: Proxy-Auto-Auth_v2.0.crx + CryptoPro-Extension-for-CAdES-Browser-Plug-in_v1.2.7.crx

Capabilities: 

- "enableVNC", true
- "acceptSslCerts", true
- "acceptInsecureCerts", true
- "sessionTimeout", 60
- "name", "myName"
- "ensureCleanSession", true

**Comment by vania-pooh** [comment]
@ghostcky I can confirm this is reproducing. Will fix soon.

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aandryashin/moon/commit/f82ef8f21d81f866c5b041a23223e08b2c180f4a.
