### ISSUE TITLE
Add documentation about required Kubernetes roles

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#67]
Not every team will be able to get cluster admin privileges.

**Comment by tomrdale** [comment]
> Not every team will be able to get cluster admin privileges.

Are you able to run moon inside kubernetes without default service account having admin, and there currently is just a lack of documentation? Or do you need to have the default service account that moon uses have admin privilages and you are creating documentation on what you need to get from your cluster admin?  Just trying to figure out what this change will provide.

**Comment by vania-pooh** [comment]
@tomrdale in fact cluster admin is not needed. The only privileges Moon needs are:
1) Launching services and pods (certainly listing them)
2) Reading resource quota information (for licensing purposes)
