### ISSUE TITLE
Unable to connect to logs on Moon-UI

### ISSUE THREAD

**Issue by donofriov** [aerokube/moon#70]
After running tests and going to moon-ui, I'm getting an error that prevents me from viewing the tests logs and the VNC viewer:

```
2018/10/10 12:38:00 Client added. 1 registered clients
2018/10/10 12:38:11 [WS_PROXY] [/ws/vnc/chrome-65-0-8cf8895a-6a44-4694-9684-9ea7b0c40e7f] [ws://localhost:8888/vnc/chrome-65-0-8cf8895a-6a44-4694-9684-9ea7b0c40e7f]
2018/10/10 12:38:12 websocketproxy: couldn't upgrade websocket: 'Origin' header value not allowed
```

![image](https://user-images.githubusercontent.com/4457953/46739077-ffe71200-cc9f-11e8-858b-ef7e584d07da.png)

We need the option to allow traffic from our custom domain.

[websocketproxy](https://github.com/koding/websocketproxy) is used to create a new client [here](https://github.com/aerokube/selenoid-ui/blob/185dedde6a84476ba2e2f31ee11e14f9af120054/main.go#L52). This uses the default upgrader which is [Gorilla's](https://github.com/gorilla/websocket). Gorilla's websocket docs describe the [Origin Considerations](https://godoc.org/github.com/gorilla/websocket#hdr-Origin_Considerations). The upgrader (https://godoc.org/github.com/gorilla/websocket#Upgrader) has a `CheckOrigin` function that by default is undefined, but if we were to define it, we could allow traffic from our custom domain.

**Comment by vania-pooh** [comment]
Related to https://github.com/aerokube/selenoid-ui/issues/113.

**Comment by vania-pooh** [comment]
Added a flag to specify allowed websocket origins for the UI. Need some time to test and release.

**Comment by vania-pooh** [comment]
@donofriov could you try whether it works with `aerokube/selenoid-ui:latest` image and the following command-line flag added: `-allowed-origin *` (star means any origin, but can also be a comma-separated list of allowed origin headers)? If that works I will do a release.

**Comment by vania-pooh** [comment]
@donofriov any chances to check?

**Comment by donofriov** [comment]
Sorry I was on holiday, taking a look now.

**Comment by donofriov** [comment]
Our custom domain is now able to connect to selenoid-ui 👍

**Comment by vania-pooh** [comment]
Released as https://github.com/aerokube/selenoid-ui/releases/tag/1.6.3. Image ref is `aerokube/selenoid-ui:1.6.3`.

**Comment by Asgoret** [comment]
**RESOLVED**


Similar issue on `aerokube/selenoid-ui:1.10.0` in okd 3.11
Any ideas?
**UPD#1:** Adding allowed origin didn't help
**UPD#2:** RBAC permission error
![error](https://user-images.githubusercontent.com/30697011/79984429-d5d7f800-84b1-11ea-939b-e06bbc2dc1a8.jpg)
