### ISSUE TITLE
Return more clear error message on templates failure

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon#97]
![image 2018-11-23 13 59 44](https://user-images.githubusercontent.com/829320/48940281-09fb6200-ef28-11e8-8721-015ae3189cc9.jpg)

**Comment by Deep27** [comment]
Я думаю, что здесь может быть проблема в настройках самого фреймворка nightwatch. Потому что у коллег на java проекте пользователь 'test' и 'guest' находятся.

**Comment by vania-pooh** [comment]
Как минимум ошибка должна быть понятнее.

**Comment by Deep27** [comment]
Вот полный конфиг Nightwatch, при котором вышеуказанная ошибка возникает:

```json
{
  "src_folders": [
    "./test/tests/",
    "./app/src/test/tests/"
  ],

  "output_folder": "reports",
  "custom_commands_path": "./test/commands/",
  "custom_assertions_path": "./test/assertions/",
  "page_objects_path": [
    "./app/src/test/page_objects/"
  ],

  "globals_path": "./test/globals.js",

  "selenium": {
    "start_process": false
  },

  "test_settings": {

    "default": {

      "selenium_host": "selenoid.apps.test.ru",
      "default_path_prefix": "/wd/hub",
      "selenium_port": 80,
      "launch_url": "http://localhost:8080",

      "desiredCapabilities": {
        "browserName": "chrome",
        "name": "CSS_Tests_Nightwatch",
        "enableVNC": true,
        "acceptSslCerts": true,
        "acceptInsecureCerts": true,
        "javascriptEnabled": true
      }
    }
  }
}
```

**Comment by Deep27** [comment]
Посмотрел в Wireshark, что передается в desiredCapabilities при запуске. Фреймворк Nightwatch переписывает name в desiredCapabilities именем теста. У нас переписывается значением "Tests\ Button\ default".

Со стороны сервера, видимо, ошибка говорит о том, что не получается эту строку обработать.

**Comment by vania-pooh** [comment]
@Deep27 да, это какая-то проблема с экранированием. Скоро разберемся.

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aandryashin/moon/commit/32927eb6fe35df173dd3cec0c59db3542f7d8846.
