### ISSUE TITLE
Invalid browser session limits are set. Please update quota properties and restart Moon.

### ISSUE THREAD

**Issue by akria18** [aerokube/moon#98]
Hello @vania-pooh 
I am getting this issue on OpenShift and im looking for help. 
Thx a lot

**Comment by akria18** [comment]
2018/11/26 08:48:48 [INIT] [Moon is now returning an error for all requests]
2018/11/26 09:33:12 [REQUEST_ERROR] [unknown] [10.120.176.94] [Rejecting user request because of invalid session quota configuration]

**Comment by vania-pooh** [comment]
@akria18 you have to create `ResourceQuota` definition with hard limit for pods.
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: max-moon-sessions
  namespace: moon
spec:
  hard:
    pods: "5"
  scopes: ["NotTerminating"]
```
Limit should be equal to `browserPodsFromLicense + numMoonPods`. E.g. without license key you are allowed to have 4 browsers pods running in parallel. Having 1 Moon replica you shoud set this resource quota to `4 + 1 = 5`.

**Comment by akria18** [comment]
In fact, im not allowed to create ResourceQuota so what should i do

**Comment by vania-pooh** [comment]
@akria18 then your cluster admin should do it. See also: https://aerokube.com/moon/latest/#_required_permissions

**Comment by akria18** [comment]
well, when i deploy moon on openshift using moon-openshift.yaml . it creates three pods and in config maps , i have set 3 versions of firefox so the hard limit should be 6?

**Comment by akria18** [comment]
because i have fixed to 6 but i am always getting the same problem @vania-pooh

**Comment by vania-pooh** [comment]
@akria18 you can use any desired number of versions. The only important parameter is total number of browser sessions being run **in parallel**. In Kubernetes terms - it is total number of pods with browsers launched by Moon. Without installing custom license you can calculate the limit as `4 + numMoonPods`. In case of [moon-openshift.yaml](https://github.com/aerokube/moon/blob/gh-pages/latest/files/moon-openshift.yaml) it should be `4 + 3 = 7` (3 pods are created for `moon`, `moon-api` and `moon-ui` respectively).

**Comment by vania-pooh** [comment]
@akria18 also you have to restart Moon after applying modifications.

**Comment by akria18** [comment]
@vania-pooh Okay and thank you so much

**Comment by akria18** [comment]
@vania-pooh I have added this in Ressource quota's Openshift. But i still getting that error
![image](https://user-images.githubusercontent.com/44463531/49076367-23a6ed00-f239-11e8-8b4e-88ab36d4ef26.png)

**Comment by akria18** [comment]
what do you think @vania-pooh

**Comment by vania-pooh** [comment]
@akria18 is your resource quota in the same namespace as Moon pods? Any more error messages in the log?

**Comment by akria18** [comment]
Yes @vania-pooh , and that's what im getting in moon's logs: 
![image](https://user-images.githubusercontent.com/44463531/49086243-57dbd700-f254-11e8-8879-17c2642967dd.png)

**Comment by akria18** [comment]
@vania-pooh the problem is with max-moon-sessions , do you have any idea how to make moon use the resource quota max-moon-sessions created by the master in quota ? 
![image](https://user-images.githubusercontent.com/44463531/49093470-7518a180-f264-11e8-91de-ecbfee92509c.png)

**Comment by vania-pooh** [comment]
@akria18 either decrease pods limit 50 to smaller value but it's simpler to generate and install a free license with e.g. 100 sessions valid until March 2019 here: https://moon.aerokube.com/ How to install: https://github.com/aerokube/moon-deploy#installing-license-key

**Comment by akria18** [comment]
Thx @vania-pooh

**Comment by akria18** [comment]
@vania-pooh 
![image](https://user-images.githubusercontent.com/44463531/49157125-562b1580-f31f-11e8-826a-e17c5cefc58b.png)

**Comment by vania-pooh** [comment]
@akria18 yep, now run your tests. :)

**Comment by akria18** [comment]
@vania-pooh  Im getting this error now 
![image](https://user-images.githubusercontent.com/44463531/49212413-47e20580-f3c2-11e8-944b-26d37c94a38c.png)

**Comment by vania-pooh** [comment]
@akria18 this capability is required - otherwise browsers will fail to start.

**Comment by akria18** [comment]
So i have to create the role bindin @vania-pooh

**Comment by vania-pooh** [comment]
@akria18 your Kubernetes namespace should allow to start pods with SYS_ADMIN capability.

**Comment by vania-pooh** [comment]
@akria18 did it help?

**Comment by akria18** [comment]
@vania-pooh  The problem as i have said , im not master so that i cant add the SYS_Admin capability

**Comment by akria18** [comment]
So Do you have any idea ?? @vania-pooh

**Comment by vania-pooh** [comment]
@akria18 this behavior is hard-coded.

**Comment by akria18** [comment]
@vania-pooh  You cannot add a feature for parametric or soft-coding for example????

**Comment by vania-pooh** [comment]
@akria18 browsers will not start then.

**Comment by akria18** [comment]
@vania-pooh, so there is no solution for that ?

**Comment by aandryashin** [comment]
please ask your system administrator to allow that capability in validation
rules.

чт, 29 нояб. 2018 г. в 18:42, akria18 <notifications@github.com>:

**Comment by vishal-yadav** [comment]
@vania-pooh, facing the same issue on gke. Using the default moon.yaml 6 pods, so should be able to open 4 parallel sessions. However it failed with above error as long as the first browser session is opened.

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: max-moon-sessions
  namespace: moon
spec:
  hard:
    pods: "6"
  scopes: ["NotTerminating"]

```

**Comment by vania-pooh** [comment]
@vishal-yadav what is your Moon version?

**Comment by vishal-yadav** [comment]
It's 1.1.9. And selenoid-ui says 0+0/0 for quota.
aerokube/moon:1.1.9
aerokube/moon-api:1.1.9
aerokube/selenoid-ui:1.6.3

Also experiencing same issue with 1.2.0 moon version.

**Comment by vania-pooh** [comment]
@vishal-yadav could you show the full `moon` container log? E.g.:
```
$ kubectl logs <moon-pod-id> -c moon -n moon
```

**Comment by vishal-yadav** [comment]
2 moon pods were running. First one pending and shows no log output while the second shows some permission issue.

```
$ kubectl get pods -n moon
NAME                  READY     STATUS    RESTARTS   AGE
moon-9856585f-dfvbv   0/3       Pending   0          8m
moon-9856585f-zfjhn   3/3       Running   0          8m

``` 
```
$ kubectl logs moon-9856585f-zfjhn -c moon -n moon
2018/12/05 14:02:00 [INIT] [Guest access is supported as user "browsers"]
2018/12/05 14:02:00 [INIT] [Using default Moon settings: failed to fetch moon-config map: configmaps "moon-config" is forbidden: User "system:serviceaccount:moon:default" cannot get configmaps in the namespace "moon"]
2018/12/05 14:02:00 [INIT] [Using aerokube/defender:1.2.0 image as defender]
2018/12/05 14:02:00 [INIT] [Using aerokube/logger:1.2.0 image as logger]
2018/12/05 14:02:00 [INIT] [Using aerokube/moon-video-recorder:1.2.0 image as videoRecorder]
2018/12/05 14:02:00 [INIT] [Listening on :4444]
2018/12/05 14:02:00 [INIT] [Found license for "Default" allowing 4 simultaneous browser sessions]
2018/12/05 14:02:00 [INIT] [Failed to get required resource quota information: resourcequotas is forbidden: User "system:serviceaccount:moon:default" cannot list resourcequotas in the namespace "moon". Please create such quota according to documentation.]
2018/12/05 14:02:00 [INIT] [Moon is now returning an error for all requests]
```

**Comment by akria18** [comment]
@vishal-yadav  I think you should give that service account the right to view in the namespace . In order to get the ressource quota to use by moon

**Comment by vania-pooh** [comment]
@vishal-yadav yep, insufficient permissions issue. Pending means insufficient CPUs \ memory to start.

**Comment by vishal-yadav** [comment]
Thank you @vania-pooh, @akria18 will get sufficient resources and permissions for moon.
