### ISSUE TITLE
Unable to locate table element in the page

### ISSUE THREAD

**Issue by vishal-yadav** [aerokube/moon#99]
**selenoid/moon** is unable to locate the table element in the web page while **selenium grid (hub/node)** is able to locate the same table element in the page.

More specifically trying to locate GKE workloads table element in 
https://console.cloud.google.com/kubernetes/workload?project=${GCP_PROJECT_ID}&workload_list_tablesize=200

GKE Environment:
----------------------
Client Version: v1.10.7
Server Version: v1.11.2-gke.18

Moon Images (from moon.yaml):
--------------------------------------
aerokube/moon:1.1.9
aerokube/moon-api:1.1.9
aerokube/selenoid-ui:1.6.3

Browser Image (from moon.yaml):
--------------------------------------
selenoid/chrome:70.0

Thanks

**Comment by vania-pooh** [comment]
@vishal-yadav any selector examples?

**Comment by vishal-yadav** [comment]
Basically it's robot/selenium test case which tries to wait for xpath table locator:
`Wait Until Element Is Visible    xpath: //table[@class="p6n-table p6n-table-pagination"]    timeout=300s  `

**Comment by vania-pooh** [comment]
@vishal-yadav could you then try whether this is reproducing with older versions, e.g. Chrome 69.0? Seems to be a Chromedriver bug.

**Comment by vishal-yadav** [comment]
Sure @vania-pooh will try to reproduce on chrome 69.0. 
JFYI chrome version was 70.0 both for selenoid/chrome and for chrome with selenium grid (hub/node).

**Comment by vishal-yadav** [comment]
Didn't workout with chrome 69.0 (same behavior with firefox as well).

**Comment by vania-pooh** [comment]
@vishal-yadav what is your Selenium client version?

**Comment by vishal-yadav** [comment]
Okay so browser VNC explained it all.
It's captcha (in addition to username/password) which comes in the way when logging to GKE using selenoid browser. While in my local system where selenium grid is setup, GKE login only asks for username and password.
Closing the issue and thanks for looking into it.

**Comment by vania-pooh** [comment]
@vishal-yadav glad to hear. :)
